name: Deploy
on: [push]

jobs:
    deploy: 
        runs-on: ubuntu-latest
        env:
            env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        
        steps:
           - name: INC Discussion Forum 
             uses: actions/checkout@v2
            
           - name: Setup Node.js
             uses: actions/setup-node@v3
             with:
                    node-version: '20'

           - name: Install pnpm
             run: npm install -g pnpm
            
           - name: Install dependencies
             run: pnpm install --force

           - name: Deploy
             run: |              
                  pnpm exec prisma generate
                  pnpm exec sst deploy --stage prod



